"""10x Visium loader utilities."""

from __future__ import annotations

import json
import warnings
from pathlib import Path
from typing import Any, Optional

import pandas as pd
from anndata import AnnData
from matplotlib.image import imread

__all__ = ["load_visium_sp_meta", "load_visium_probe"]


# Similar to scanpy.read_visium
# https://github.com/scverse/scanpy/blob/main/scanpy/readwrite.py#L356-L512
def load_visium_sp_meta(
    adata: AnnData, path_to_spatial: str | Path, library_id: Optional[str] = None
) -> AnnData:
    """Helper function to load Visium spatial metadata.

    Parameters
    ----------
    adata
        Annotated data matrix to store the spatial metadata.
    path_to_spatial
        Path to the `spatial` folder generated by Space Ranger.
    library_id
        Library ID of the spatial data.

    Returns
    -------
    anndata : anndata.AnnData
        AnnData with spatial metadata.
    """
    if library_id is None:  # default library_id
        library_id = "library_id"

    adata.uns["spatial"] = dict()
    adata.uns["spatial"][library_id] = dict()

    path = Path(path_to_spatial)
    tissue_positions_file = (
        path / "tissue_positions.csv"
        if (path / "tissue_positions.csv").exists()
        else path / "tissue_positions_list.csv"
    )

    files = dict(
        tissue_positions_file=tissue_positions_file,
        scalefactors_json_file=path / "scalefactors_json.json",
        hires_image=path / "tissue_hires_image.png",
        lowres_image=path / "tissue_lowres_image.png",
    )

    # load images
    adata.uns["spatial"][library_id]["images"] = dict()
    for res in ["hires", "lowres"]:
        try:
            adata.uns["spatial"][library_id]["images"][res] = imread(
                str(files[f"{res}_image"])
            )
        except Exception:
            warnings.warn(
                f"Missing '{res}' image in {path_to_spatial}. Will be ignored.",
                UserWarning,
                stacklevel=2,
            )
            adata.uns["spatial"][library_id]["images"][res] = None

    # read json scalefactors
    with open(files["scalefactors_json_file"]) as f:
        adata.uns["spatial"][library_id]["scalefactors"] = json.load(f)

    # read coordinates
    positions = pd.read_csv(
        files["tissue_positions_file"],
        header=0,
        index_col=0,
    )
    positions.columns = [
        "in_tissue",
        "array_row",
        "array_col",
        "pxl_col_in_fullres",
        "pxl_row_in_fullres",
    ]

    # add coordinates to spot metadata
    adata.obs = adata.obs.join(positions, how="left")
    adata.obsm["spatial"] = adata.obs[
        ["pxl_row_in_fullres", "pxl_col_in_fullres"]
    ].to_numpy()
    adata.obs.drop(
        columns=["pxl_row_in_fullres", "pxl_col_in_fullres"],
        inplace=True,
    )

    return adata


def load_visium_probe(
    path: str | Path,
    *,
    counts_file: str = "raw_probe_bc_matrix.h5",
    library_id: Optional[str] = None,
    load_spatial: bool = True,
    counts_layer_name: str = "counts",
    filtered_counts_file: bool = True,
    return_type: str = "anndata",
) -> Any:
    """Load standard Visium Space Ranger probe-based outputs.

    Reads the probe-level count matrix (``raw_probe_bc_matrix.h5`` by default)
    from a Space Ranger ``outs`` directory and optionally attaches spatial
    metadata (coordinates, images, scale factors) from the ``spatial/`` subfolder.

    This is the standard-resolution Visium counterpart of
    :func:`load_visiumhd_probe` (which handles Visium HD multi-bin outputs).

    Parameters
    ----------
    path
        Path to the Space Ranger ``outs`` directory, e.g.
        ``<run_id>/outs``.  Must contain the HDF5 count matrix and,
        when ``load_spatial=True``, a ``spatial/`` subfolder.
    counts_file
        Name of the HDF5 count matrix file inside ``path``.
        Typical choices:

        * ``"raw_probe_bc_matrix.h5"`` — all barcodes, probe-level features
          (default; preserves per-probe information).
        * ``"raw_feature_bc_matrix.h5"`` — all barcodes, gene-level features.
        * ``"filtered_feature_bc_matrix.h5"`` — tissue barcodes only,
          gene-level features.
    library_id
        Library identifier stored in ``adata.uns["spatial"]`` (AnnData mode)
        or used to name SpatialData elements (SpatialData mode).
        Defaults to the parent directory name of *path*.
    load_spatial
        Whether to load spatial metadata (tissue positions, images,
        scale factors).  Only used when ``return_type="anndata"``.
    counts_layer_name
        Layer name for the raw count matrix.  The counts are stored in
        ``adata.layers[counts_layer_name]``.
    filtered_counts_file
        If ``True`` (default), keep only in-tissue barcodes that appear in
        ``filtered_feature_bc_matrix.h5``.  If ``False``, keep all barcodes
        from ``counts_file`` (including background spots).
    return_type
        Output format.

        * ``"anndata"`` (default) — return an :class:`~anndata.AnnData`
          with spatial metadata in ``.obsm["spatial"]`` and ``.uns["spatial"]``.
        * ``"spatialdata"`` — return a :class:`~spatialdata.SpatialData` object
          built by ``spatialdata_io.visium()``, with probe-level ``var``
          metadata restored and a counts layer added.  Suitable for use with
          :class:`~splisosm.SplisosmFFT`.

    Returns
    -------
    anndata.AnnData or spatialdata.SpatialData
        When ``return_type="anndata"``:

        * ``.X`` / ``.layers[counts_layer_name]`` — sparse count matrix
        * ``.var`` — feature (probe or gene) metadata
        * ``.obs`` — barcode metadata with ``in_tissue``, ``array_row``,
          ``array_col`` (when ``load_spatial=True``)
        * ``.obsm["spatial"]`` — ``(n_spots, 2)`` pixel coordinates
        * ``.uns["spatial"]`` — images and scale factors

        When ``return_type="spatialdata"``:

        * ``sdata.tables["table"]`` — AnnData with probe-level counts in
          ``.layers[counts_layer_name]`` and full probe metadata in ``.var``
        * ``sdata.shapes[dataset_id]`` — spot geometries
        * ``sdata.images`` — tissue images at multiple resolutions

    Raises
    ------
    FileNotFoundError
        If the counts file or spatial directory is missing.

    Examples
    --------
    Load as AnnData (for :class:`~splisosm.SplisosmNP`):

    >>> from splisosm.io import load_visium_probe
    >>> adata = load_visium_probe("sample/outs")

    Load as SpatialData (for :class:`~splisosm.SplisosmFFT`):

    >>> sdata = load_visium_probe("sample/outs", return_type="spatialdata")
    """
    try:
        import scanpy as sc
    except ImportError as e:
        raise ImportError(
            "scanpy is required for load_visium_probe(). "
            "Install it via `pip install scanpy`."
        ) from e

    path = Path(path)
    h5_file = path / counts_file
    if not h5_file.exists():
        raise FileNotFoundError(
            f"Count matrix not found: {h5_file}\n"
            f"Available .h5 files: {sorted(p.name for p in path.glob('*.h5'))}"
        )

    if library_id is None:
        library_id = path.parent.name

    # ------------------------------------------------------------------
    # SpatialData mode
    # ------------------------------------------------------------------
    if return_type == "spatialdata":
        try:
            from spatialdata_io.readers.visium import visium as _visium_reader
        except ImportError as e:
            raise ImportError(
                "spatialdata-io is required for return_type='spatialdata'. "
                "Install it via `pip install spatialdata-io`."
            ) from e
        try:
            from spatialdata.models import TableModel
        except ImportError as e:
            raise ImportError(
                "spatialdata is required for return_type='spatialdata'. "
                "Install it via `pip install spatialdata`."
            ) from e

        # 1. Build the SpatialData scaffold (shapes, images, coordinate
        #    systems) using the gene-level matrix.  This gives us the
        #    canonical Visium spot geometry and spatial metadata.
        scaffold_counts = (
            "filtered_feature_bc_matrix.h5"
            if filtered_counts_file
            else "raw_feature_bc_matrix.h5"
        )
        sdata = _visium_reader(
            path=str(path),
            counts_file=scaffold_counts,
            dataset_id=library_id,
        )

        # 2. Read the probe-level matrix with full var metadata.
        adata_probe = sc.read_10x_h5(str(h5_file), gex_only=False)
        adata_probe.var_names_make_unique()

        # Align barcodes: keep only barcodes present in the scaffold
        # table (which carries array_row/col and spot_id).
        scaffold = sdata.tables["table"]
        common_bcs = scaffold.obs_names.intersection(adata_probe.obs_names)
        adata_probe = adata_probe[common_bcs].copy()

        # Copy spatial obs columns from the scaffold table.
        for col in ["in_tissue", "array_row", "array_col", "spot_id", "region"]:
            if col in scaffold.obs.columns:
                adata_probe.obs[col] = scaffold.obs.loc[common_bcs, col].values

        # Register as a SpatialData table annotating the same shapes element.
        adata_probe.obs["region"] = scaffold.obs.loc[common_bcs, "region"].values
        adata_probe.obs["spot_id"] = scaffold.obs.loc[common_bcs, "spot_id"].values
        if "spatialdata_attrs" in adata_probe.uns:
            del adata_probe.uns["spatialdata_attrs"]
        adata_probe = TableModel.parse(
            adata_probe,
            region=library_id,
            region_key="region",
            instance_key="spot_id",
        )

        # Copy obsm from scaffold (spatial pixel coordinates).
        if "spatial" in scaffold.obsm:
            adata_probe.obsm["spatial"] = scaffold.obsm["spatial"][
                scaffold.obs_names.get_indexer(common_bcs)
            ]

        adata_probe.layers[counts_layer_name] = adata_probe.X.copy()

        # 3. Replace the gene-level table with the probe-level table.
        del sdata.tables["table"]
        sdata.tables["table"] = adata_probe

        return sdata

    # ------------------------------------------------------------------
    # AnnData mode (default)
    # ------------------------------------------------------------------
    if return_type != "anndata":
        raise ValueError(
            f"Unknown return_type={return_type!r}. "
            f"Expected 'anndata' or 'spatialdata'."
        )

    # Read the 10x HDF5 count matrix
    adata = sc.read_10x_h5(str(h5_file), gex_only=False)
    adata.var_names_make_unique()

    # Filter to in-tissue barcodes if requested
    if filtered_counts_file:
        filtered_h5 = path / "filtered_feature_bc_matrix.h5"
        if filtered_h5.exists():
            filtered_bcs = sc.read_10x_h5(str(filtered_h5)).obs_names
            keep = adata.obs_names.isin(filtered_bcs)
            adata = adata[keep].copy()
        else:
            warnings.warn(
                f"filtered_feature_bc_matrix.h5 not found at {path}. "
                f"Returning all barcodes.",
                UserWarning,
                stacklevel=2,
            )

    # Store raw counts in a named layer
    adata.layers[counts_layer_name] = adata.X.copy()

    # Attach spatial metadata
    if load_spatial:
        spatial_dir = path / "spatial"
        if not spatial_dir.exists():
            warnings.warn(
                f"Spatial directory not found at {spatial_dir}. "
                f"Skipping spatial metadata loading.",
                UserWarning,
                stacklevel=2,
            )
        else:
            load_visium_sp_meta(adata, spatial_dir, library_id=library_id)

    # Ensure obs index is string (consistent with other loaders)
    adata.obs_names = adata.obs_names.astype(str)

    return adata
